from waflib import Configure
Configure.autoconfig = True


def options(opt):
    opt.load('compiler_cxx')


def configure(cnf):
    cnf.load('compiler_cxx')


def build(bld):
    bld.recurse('third-party')

    bld.stlib(target='date_util',
              source=['date_util.cpp'])

    bld.program(target='date_util_test',
                source=['date_util_test.cpp'],
                use=['date_util',
                     'gmock_main'])


# vim: set ft=python expandtab ts=4 sw=4 sts=4 tw=100:
